### PR TITLE
Redefining Total Contributions Function #4

### PR DESCRIPTION
**Pull request by pranshumaheshwari**

### CODE REVIEW

**Comment by pranshumaheshwari** [comment]
I don't know why but the Unnecessary block check is getting an issue, and we cannot remove the blocks in graphql query as far as I know anyway.

**Comment by capturemathan** [comment]
> I don't know why but the Unnecessary block check is getting an issue, and we cannot remove the blocks in graphql query as far as I know anyway.

Good job bro. Also could you please attach the `console` O/P or `Screenshot` after running the main file to ensure the proper working of the code addition 😉. I'll take care of the `failing check`

**Comment by pranshumaheshwari** [comment]
Console Screenshot

**Comment by capturemathan** [comment]
Just a small addition to README. Please mention the checkboxes to select in the `Select the scopes, or permissions, you'd like to grant this token. To use your token to access repositories from the command line, select repo.` in this site
`https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token` as it would help the user.

**Comment by pranshumaheshwari** [comment]
> 
> 
> Just a small addition to README. Please mention the checkboxes to select in the `Select the scopes, or permissions, you'd like to grant this token. To use your token to access repositories from the command line, select repo.` in this site
> `https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token` as it would help the user.

Done

**Pull request merged**
